version: '3'

services:
  app:
    platform: linux/amd64
    build: .
#    tty: true
#    stdin_open: true
#    entrypoint: ash
    working_dir: /var/work/go-container
    user: root
    volumes:
      - type: bind
        source: .
        target: /var/work/go-container