version: '3'

services:
  app:
    build: .
    tty: true
    stdin_open: true
    entrypoint: bash
    working_dir: /var/work
    ports:
      - "6006:6006"
    volumes:
      - type: bind
        source: .
        target: /var/work
